### ISSUE TITLE
Windows support!

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#131]
So windows support will need some fiddling around with statemachine. Probably moving it into it's own module with a submodule for windows and linux. For the windows side of things this looks to be a good reference. https://msdn.microsoft.com/en-us/library/ms809754.aspx 

Here are some things that will need moving around/changing

* [ ] pdb parsing to get source code locations https://crates.io/crates/pdb 
* [ ] LLVM coverage https://github.com/xd009642/tarpaulin/issues/549 
* [ ] Optional: do the ptrace equivalent here are the unsafe bindings to the API https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Diagnostics/Debug/index.html

**Comment by xd009642** [comment]
https://docs.microsoft.com/en-us/windows/win32/debug/creating-a-basic-debugger

**Comment by xd009642** [comment]
So this is now merged and some point this week there shall be a new release on crates.io (probably tomorrow). closing this issue in favour of #549
